name: MAIN - Build and Deploy - AWS

on:
  pull_request:
    branches: [ "main" ]

env:
  applicationfolder: smartfit
  AWS_REGION: us-east-1
  S3BUCKET: codedeploystack-webappdeploymentbucket-hewnfbairdwf
  working_directory: ./smartfit/


jobs:
  deploy:
    name: Deploy in S3
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ${{ env.working_directory }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '${{ env.working_directory }}package-lock.json'

      - name: Build project
        run: |
          npm ci 
          npm run build --if-present

      - name: Upload Artifact to s3
        working-directory: ${{ env.applicationfolder }}/dist/smartfit
        run: aws s3 cp browser s3://${{ env.S3BUCKET }}/ --recursive